# Generated by Django 3.2.23 on 2023-11-23 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0002_write_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='write',
            name='category',
        ),
    ]
