# Generated by Django 4.2.7 on 2023-11-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(null=True),
        ),
    ]
