# Generated by Django 3.2.23 on 2023-11-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0003_remove_write_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='write',
            name='category',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
